### ISSUE TITLE
Unable to get past login

### ISSUE THREAD

**Issue by c-shankar** [KryDos/todoist-linux#11]
OS: Xubuntu 18.04 x64
Immediately after logging in, I'm stuck at this message. It doesn't redirect either. On clicking the link, it only opens the page in a web browser.
![image](https://user-images.githubusercontent.com/3977387/41197314-9bb29432-6c76-11e8-9e23-70414e2357cc.png)

**Comment by KryDos** [comment]
hey @c-shankar 
thanks a lot for letting me know, I thought it fixed but it's definitely not. 
I'll let you know when it fixed. 

P.S.
The app should work and you will be logged in if you'll close and open it.

**Comment by KryDos** [comment]
hi @c-shankar the issue should be fixed in [latest release (1.8)](https://github.com/KryDos/todoist-linux/releases/tag/1.8) 

Basically I'm just checking if you pressed that link then the app window will be reloaded. Should work fine. 

Let me know if you still has the issue.

**Comment by drmercer** [comment]
I just installed this today and I'm having the same error: 
![Login redirect page](https://i.imgur.com/xkVMBpm.png)

Like described above, clicking the link just opens it in Firefox (my default browser).

**Comment by drmercer** [comment]
Doing a `pkill todoist` and then Tray Icon > Quit and then restarting worked for me. (I believe I tried Tray Icon > Quit and then restarting before, and it didn't work.)

**Comment by sollymay** [comment]
I still experience this issue. after successfully providing credentials, I get the same screen and can't get out of it :( 

![Screenshot from 2019-03-09 15-03-39](https://user-images.githubusercontent.com/6496698/54076776-2758ff80-427d-11e9-8e7f-d04e7e09e131.png)

**Comment by KryDos** [comment]
hi @sollymay 
thanks for the report. 

The issue has to be fixed in version 1.15 which can be found [HERE](https://github.com/KryDos/todoist-linux/releases/tag/1.15)

**Comment by sollymay** [comment]
Thank you @KryDos! Looks like it is solved now!
